'use client'

import { imageURL } from '@/lib/assets'
import { useState } from 'react'
type Entry = { id:number; name:string; message:string; date:string }
type Airport = { iata:string; city:string; name:string }
export default function CheckinDesk({ entries, airports }: { entries:Entry[]; airports:Airport[] }) {
  const [name,setName]=useState(''), [base,setBase]=useState(''), [message,setMessage]=useState('')
  const [issued,setIssued]=useState(false), [busy,setBusy]=useState(false), [sent,setSent]=useState(false), [error,setError]=useState('')
  const airport=airports.find(a=>a.iata===base.toUpperCase().trim())
  const code=airport?.iata || '–––'
  const pass=<div className={`visitor-boarding-pass airways-pass ${issued?'pass-issued':''}`}>
    <div className="pass-band"><div className="airways-brand"><img src={imageURL('/images/card/merak-mark.svg')} width={32} height={29} alt="" /><span>MERAK AIRWAYS<small>THE PAW-LACE™ SUITE</small></span></div><span>登机牌<br />BOARDING PASS</span></div>
    <div className="airways-body"><div className="pass-main"><div className="pass-passenger"><span>PASSENGER / 旅客</span><strong>{name.trim()||'你的名字'}</strong></div>
    <div className="pass-route"><div><strong>{code}</strong><span>{airport?.city||'你的 Base 机场'}</span></div><div className="pass-flight-line" aria-hidden="true">✈</div><div><strong>HGH</strong><span>杭州 · 萧山</span></div></div>
    <div className="pass-details"><div><span>航班 / FLIGHT</span><b>MK 518</b></div><div><span>登机口 / GATE</span><b>HELLO</b></div><div><span>座位 / SEAT</span><b>1A</b></div></div>
    <div className="pass-lounge"><span>LOUNGE ACCESS / 候机室通行</span><p>{message.trim()||'这一程，很高兴遇见你。'}</p></div></div>
    <aside className="visitor-pass-stub" aria-label="登机牌副联"><span>旅客存根</span><strong>{name.trim()||'你的名字'}</strong><div><small>FROM</small><b>{code}</b></div><div><small>TO</small><b>HGH</b></div><div><small>FLIGHT / SEAT</small><b>MK 518 / 1A</b></div><div className="pass-barcode" aria-hidden="true" /></aside></div>
    <div className="pass-tear"><span>{sent?'已提交 · 等待审核':issued?'已签发 · 仅自己可见':'VISITOR EDITION'}</span><small>到访纪念 · 非真实乘机凭证</small></div>
  </div>
  return <><section className="boarding-desk" aria-labelledby="boarding-title"><div className="boarding-controls"><p className="kicker">SELF CHECK-IN / 自助值机</p><h2 id="boarding-title">从你的 Base，<br />飞到我的杭州。</h2><p>一个名字，一座机场。<br />领张登机牌，就算来过啦。</p>{!issued?<form onSubmit={e=>{e.preventDefault();if(!airport){setError('请选一个列表中的机场，或输入有效的三字码。');return}setError('');setIssued(true)}}>
    <label>旅客姓名<input name="name" value={name} onChange={e=>setName(e.target.value)} maxLength={40} required autoComplete="nickname" placeholder="昵称就好" /></label>
    <label>Base 机场<input list="base-airports" value={base} onChange={e=>setBase(e.target.value)} required maxLength={3} placeholder="输入三字码，如 PVG" autoComplete="off" /><datalist id="base-airports">{airports.map(a=><option value={a.iata} key={a.iata}>{a.city} · {a.name}</option>)}</datalist></label><div className="base-shortcuts" role="group" aria-label="常用 Base 机场">{['PEK','PKX','PVG','CAN','SZX','HGH'].map(a=><button type="button" key={a} aria-pressed={base===a} onClick={()=>setBase(a)}>{a}</button>)}</div>
    <label>捎句话 <span>可不填 · 最多 60 字</span><input name="message" value={message} onChange={e=>setMessage(e.target.value)} maxLength={60} placeholder="下次杭州见！" /></label><button className="issue-pass" type="submit">领取登机牌 <span aria-hidden="true">↗</span></button>
  </form>:<div className="boarding-confirm"><h3 role="status">登机牌已签发。</h3><p>{sent?'收到啦，审核通过后会出现在下方的到访记录。':'可以自己留着，也可以把这次到访留在这里。'}</p>{!sent&&<form onSubmit={async e=>{e.preventDefault();if(busy)return;setBusy(true);setError('');const form=new FormData(e.currentTarget);try{const res=await fetch('/api/checkins/submit',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,baseAirport:code,message,consent:form.get('consent')==='on',website:form.get('website')})});if(res.ok)setSent(true);else {const result=await res.json();setError(result.error||'提交失败，请稍后重试。')}}catch{setError('连接失败，登机牌仍保留在这里。')}finally{setBusy(false)}}}><div className="checkin-trap" aria-hidden="true"><input name="website" tabIndex={-1} autoComplete="off" aria-label="网站" /></div><label className="boarding-consent"><input type="checkbox" name="consent" required />同意审核后公开昵称、Base 机场和短句。</label><button className="issue-pass" disabled={busy}>{busy?'正在提交…':'留下这次到访'}</button></form>}<button className="pass-reset" type="button" disabled={busy} onClick={()=>{setIssued(false);setSent(false);setError('')}}>修改登机牌</button></div>}{error&&<p role="alert" className="letter-error">{error}</p>}</div><div className="boarding-preview">{pass}<p>如果你也在杭州，那就不赶飞机了，找天一起坐坐。</p></div></section>
    <section className="arrival-board" aria-labelledby="arrival-title"><header><div><p className="kicker">ARRIVALS / 到访记录</p><h2 id="arrival-title">他们也来过。</h2></div><span>审核通过后在这里见</span></header>{entries.length?<div className="arrival-list">{entries.map(entry=>{const match=entry.message.match(/^BASE ([A-Z]{3}) → HGH(?:\n(.*))?$/s);return <article key={entry.id}><span className="arrival-origin">{match?match[1]:'访客'} <i>—</i> HGH</span><strong>{entry.name}</strong><p>{match?match[2]||'来杭州坐坐。':entry.message}</p><time>{entry.date}</time></article>})}</div>:<div className="arrivals-empty"><span aria-hidden="true">––– → HGH</span><p>还没有公开的到访记录。<br /><small>第一班，等你。</small></p></div>}</section></>
}
